<a href="https://colab.research.google.com/github/HpDiniz/Analise-Financeira/blob/main/Resultado_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

import numpy as np
import pandas as pd
import math
import matplotlib.pyplot as plt
from dateutil.relativedelta import relativedelta
import seaborn as sns
from sqlalchemy import create_engine
import requests
import pickle

import math
import re
import bs4
import json
import pickle
import requests
import datetime
import dateutil
import itertools
import statistics

from datetime import date

import statsmodels.api as sm
from matplotlib import pyplot
import matplotlib.pyplot as plt

# Avaliando os resultados
from numpy import sqrt
from sqlalchemy import create_engine

In [2]:
# from google.colab import drive
# drive.mount('/content/drive')

In [3]:
uses_real_estate = ["Não","Não", "Sim", "Sim"]

In [ ]:
# Target = 'all'
# Target = 'tijolo'
# Target = 'hibrido'
Target = 'papel'

In [ ]:
# with open(f'    drive/MyDrive/Colab Notebooks/dados_artigo/result_{Target}.txt', 'rb') as f:
with open(f'result_{Target}.txt', 'rb') as f:
  results = pickle.load(f)

rmses6 = {}
rmses1 = {}

for i in results:
  if (results[i]['window_size'] == 1):
    rmses1[int(i.split('.')[0])] = list(results[i]['error'])
  else:
    rmses6[int(i.split('.')[0])] = list(results[i]['error'])

rmses1 = pd.DataFrame(rmses1)
rmses6 = pd.DataFrame(rmses6)

In [ ]:
df_1M = pd.DataFrame()

df_1M['RMSE'] = pd.DataFrame(rmses1).apply(lambda column : mean_squared_error(column, np.zeros(len(column)), squared=False))
df_1M['MAE'] = pd.DataFrame(rmses1).apply(lambda column : mean_absolute_error(column, np.zeros(len(column))))
df_1M['Modelo'] = rmses1.apply(lambda row : 'PyTorch LSTM'if row.name >= 13 else 'LSTM', axis=1 )
df_1M['Meses'] = 1
df_1M = df_1M[['Modelo','Meses', 'RMSE', 'MAE']]
df_1M
# df_1M.sort_values(['RMSE', 'MAE'])
# df_1M.sort_values(['MAE', 'RMSE'])

          Modelo  Meses      RMSE       MAE
13  PyTorch LSTM      1  0.068768  0.050003
14  PyTorch LSTM      1  0.193299  0.116976
15  PyTorch LSTM      1  0.064787  0.044921
16  PyTorch LSTM      1  0.124830  0.088154

In [ ]:
df_6M = pd.DataFrame()

df_6M['RMSE'] =rmses6.apply(lambda column : mean_squared_error(column, np.zeros(len(column)), squared=False))
df_6M['MAE'] =rmses6.apply(lambda column : mean_absolute_error(column, np.zeros(len(column))))
df_6M['Modelo'] = rmses1.apply(lambda row : 'PyTorch LSTM' if row.name >= 13 else 'LSTM', axis=1 )
df_6M['Meses'] = 6
df_6M = df_6M[['Modelo','Meses', 'RMSE', 'MAE']]
df_6M
# df_6M.sort_values(['RMSE', 'MAE'])
# df_6M.sort_values(['MAE', 'RMSE'])

          Modelo  Meses      RMSE       MAE
13  PyTorch LSTM      6  0.102964  0.078979
14  PyTorch LSTM      6  0.112820  0.085063
15  PyTorch LSTM      6  0.102369  0.076988
16  PyTorch LSTM      6  0.108567  0.082351

In [ ]:
best_models = df_1M.query("Modelo == 'PyTorch LSTM'").sort_values(['RMSE', 'MAE']).head(1)
best_models = pd.concat([best_models, df_6M.query("Modelo == 'PyTorch LSTM'").sort_values(['RMSE', 'MAE']).head(1)])
best_models

          Modelo  Meses      RMSE       MAE
15  PyTorch LSTM      1  0.064787  0.044921
15  PyTorch LSTM      6  0.102369  0.076988